default:
  tags:
    - Terraform

variables:
  TERRAFORM_DESTROY: "NO"
  TERRAFORM_APPLY: "YES"
  TERRAFORM_VERSION: "1.6.2"

stages:
  - terraform-init
  - terraform-fmt-validate
  - terraform-plan
  - terraform-apply
  - terraform-destroy

job-check-terraform-version:
  stage: terraform-init
  rules:
    - if: $TERRAFORM_DESTROY == "NO" && $TERRAFORM_APPLY =="YES"
  script:
    - pwd #&& ls -al && terraform version

job-run-terraform-init:
  stage: terraform-init
  rules:
    - if: $TERRAFORM_DESTROY == "NO"
  script:
    - pwd
    - echo $AWS_ACCESS_KEY_ID
    - echo $AWS_SECRET_ACCESS_KEY
    - terraform init

job-run-terraform-fmt-validate:
  stage: terraform-fmt-validate
  rules:
    - if: $TERRAFORM_DESTROY == "NO" && $TERRAFORM_APPLY =="YES"
  script:
    - pwd
    - echo $AWS_ACCESS_KEY_ID
    - echo $AWS_SECRET_ACCESS_KEY
    - terraform fmt && terraform validate
